In [1]:
#vamos comeÃ§ar trazendo nossas bibliotecas de processamento
import pandas as pd
import numpy as np

#tambÃ©m vamos pegar uma biblioteca de tempo 
import timeit

#e vamos pegar um dataframe de Ceus dos US
df = pd.read_csv('/content/census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [2]:
# A primeira das expressÃµes idiomÃ¡ticas de pandas sobre as quais eu gostaria de falar Ã© chamada de encadeamento de mÃ©todos. A ideia geral por trÃ¡s
# encadeamento de mÃ©todos Ã© que cada mÃ©todo em um objeto retorna uma referÃªncia a esse objeto. A beleza disso Ã©
# que vocÃª pode condensar muitas operaÃ§Ãµes diferentes em um DataFrame, por exemplo, em uma linha ou pelo menos uma
# declaraÃ§Ã£o de cÃ³digo.

# Aqui estÃ¡ a maneira pandorÃ¡vel de escrever cÃ³digo com encadeamento de mÃ©todos. Neste cÃ³digo eu vou retirar o estado
# e nomes de cidades como um Ã­ndice mÃºltiplo, e farei isso apenas para dados que tenham um nÃ­vel de resumo de 50,
# que neste conjunto de dados sÃ£o dados em nÃ­vel de condado. Vou renomear uma coluna tambÃ©m, apenas para tornÃ¡-la um pouco mais legÃ­vel

(df.where(df['SUMLEV']==50)
    .dropna()
    .set_index(['STNAME','CTYNAME'])
    .rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'}))

                           SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County       50.0     3.0       6.0    1.0     1.0
        Baldwin County       50.0     3.0       6.0    1.0     3.0
        Barbour County       50.0     3.0       6.0    1.0     5.0
        Bibb County          50.0     3.0       6.0    1.0     7.0
        Blount County        50.0     3.0       6.0    1.0     9.0
...                           ...     ...       ...    ...     ...
Wyoming Sweetwater County    50.0     4.0       8.0   56.0    37.0
        Teton County         50.0     4.0       8.0   56.0    39.0
        Uinta County         50.0     4.0       8.0   56.0    41.0
        Washakie County      50.0     4.0       8.0   56.0    43.0
        Weston County        50.0     4.0       8.0   56.0    45.0

                           CENSUS2010POP  Estimates Base 2010  \
STNAME  CTYNAME
Alabama Autauga County           54571.0              54571.0
        Baldwin County          182265.0             182265.0
        Barbour County           27457.0              27457.0
        Bibb County              22915.0              22919.0
        Blount County            57322.0              57322.0
...                                  ...                  ...
Wyoming Sweetwater County        43806.0              43806.0
        Teton County             21294.0              21294.0
        Uinta County             21118.0              21118.0
        Washakie County           8533.0               8533.0
        Weston County             7208.0               7208.0

                           POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
STNAME  CTYNAME
Alabama Autauga County             54660.0          55253.0          55175.0
        Baldwin County            183193.0         186659.0         190396.0
        Barbour County             27341.0          27226.0          27159.0
        Bibb County                22861.0          22733.0          22642.0
        Blount County              57373.0          57711.0          57776.0
...                                    ...              ...              ...
Wyoming Sweetwater County          43593.0          44041.0          45104.0
        Teton County               21297.0          21482.0          21697.0
        Uinta County               21102.0          20912.0          20989.0
        Washakie County             8545.0           8469.0           8443.0
        Weston County               7181.0           7114.0           7065.0

                           ...  RDOMESTICMIG2011  RDOMESTICMIG2012  \
STNAME  CTYNAME            ...
Alabama Autauga County     ...          7.242091         -2.915927
        Baldwin County     ...         14.832960         17.647293
        Barbour County     ...         -4.728132         -2.500690
        Bibb County        ...         -5.527043         -5.068871
        Blount County      ...          1.807375         -1.177622
...                        ...               ...               ...
Wyoming Sweetwater County  ...          1.072643         16.243199
        Teton County       ...         -1.589565          0.972695
        Uinta County       ...        -17.755986         -4.916350
        Washakie County    ...        -11.637475         -0.827815
        Weston County      ...        -11.752361         -8.040059

                           RDOMESTICMIG2013  RDOMESTICMIG2014  \
STNAME  CTYNAME
Alabama Autauga County            -3.012349          2.265971
        Baldwin County            21.845705         19.243287
        Barbour County            -7.056824         -3.904217
        Bibb County               -6.201001         -0.177537
        Blount County             -1.748766         -2.062535
...                                     ...               ...
Wyoming Sweetwater County         -5.339774        -14.252889
        Teton County              19.525929         14.143021
        Uinta County              -6.902954        -14.215862
        Washakie County           -2.013502        -17.781491
        Weston County             12.372583          1.533635

                           RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
STNAME  CTYNAME
Alabama Autauga County            -2.530799     7.606016    -2.626146
        Baldwin County            17.197872    15.844176    18.559627
        Barbour County           -10.543299    -4.874741    -2.758113
        Bibb County                0.177258    -5.088389    -4.363636
        Blount County             -1.369970     1.859511    -0.848580
...                                     ...          ...          ...
Wyoming Sweetwater County        -14.248864     1.255221    16.243199
        Teton County              -0.564849     0.654527     2.408578
        Uinta County             -12.127022   -18.136812    -5.536861
        Washakie County            1.682288   -11.990126    -1.182592
        Weston County              6.935294   -12.032179    -8.040059

                           RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County       -2.722002     2.592270    -2.187333
        Baldwin County       22.727626    20.317142    18.293499
        Barbour County       -7.167664    -3.978583   -10.543299
        Bibb County          -5.403729     0.754533     1.107861
        Blount County        -1.402476    -1.577232    -0.884411
...                                ...          ...          ...
Wyoming Sweetwater County    -5.295460   -14.075283   -14.070195
        Teton County         21.160658    16.308671     1.520747
        Uinta County         -7.521840   -14.740608   -12.606351
        Washakie County      -2.250385   -18.020168     1.441961
        Weston County        12.372583     1.533635     6.935294

[3142 rows x 98 columns]

In [3]:
# Vamos entender o que foi feito. Primeiro, usamos a funÃ§Ã£o where() no dataframe e passamos uma mÃ¡scara booleana que
# sÃ³ Ã© verdadeiro para as linhas em que SUMLEV Ã© igual a 50. Isso indica em nossos dados de origem que os dados
# Ã© resumido em nÃ­vel de condado. Com o resultado da funÃ§Ã£o where() avaliada, eliminamos
# valores. Lembre-se de que .where() nÃ£o descarta valores ausentes por padrÃ£o. Em seguida, definimos um Ã­ndice no resultado de
# este. Neste caso, configurei para o nome do estado seguido pelo nome do condado. Finalmente. Eu renomeio uma coluna para
# tornÃ¡-lo mais legÃ­vel. Note que ao invÃ©s de escrever tudo isso em uma linha, como eu poderia ter feito, eu comecei o
# declaraÃ§Ã£o com um parÃªntese, que diz ao python que vou estender a declaraÃ§Ã£o em vÃ¡rias linhas para
# legibilidade.

In [4]:
# Aqui estÃ¡ uma maneira mais tradicional e nÃ£o-pandorÃ¡vel de escrever isso. NÃ£o hÃ¡ nada de errado com este cÃ³digo no
# sentido funcional, vocÃª pode atÃ© entender melhor como uma nova pessoa no idioma. Ã‰ apenas
# nÃ£o Ã© tÃ£o pandorÃ¡vel quanto o primeiro exemplo.

df = df[df['SUMLEV']==50] # Vou usar o operador de indexaÃ§Ã£o sobrecarregado [] que descarta nans 
# inserindo um novo index para nosso dataframe e passando inplace para dizer que Ã© uma mudanÃ§a permanente 
df.set_index(['STNAME','CTYNAME'], inplace=True)
# renomeando nome de coluna 
df.rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'})

                           SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County         50       3         6      1       1
        Baldwin County         50       3         6      1       3
        Barbour County         50       3         6      1       5
        Bibb County            50       3         6      1       7
        Blount County          50       3         6      1       9
...                           ...     ...       ...    ...     ...
Wyoming Sweetwater County      50       4         8     56      37
        Teton County           50       4         8     56      39
        Uinta County           50       4         8     56      41
        Washakie County        50       4         8     56      43
        Weston County          50       4         8     56      45

                           CENSUS2010POP  Estimates Base 2010  \
STNAME  CTYNAME
Alabama Autauga County             54571                54571
        Baldwin County            182265               182265
        Barbour County             27457                27457
        Bibb County                22915                22919
        Blount County              57322                57322
...                                  ...                  ...
Wyoming Sweetwater County          43806                43806
        Teton County               21294                21294
        Uinta County               21118                21118
        Washakie County             8533                 8533
        Weston County               7208                 7208

                           POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
STNAME  CTYNAME
Alabama Autauga County               54660            55253            55175
        Baldwin County              183193           186659           190396
        Barbour County               27341            27226            27159
        Bibb County                  22861            22733            22642
        Blount County                57373            57711            57776
...                                    ...              ...              ...
Wyoming Sweetwater County            43593            44041            45104
        Teton County                 21297            21482            21697
        Uinta County                 21102            20912            20989
        Washakie County               8545             8469             8443
        Weston County                 7181             7114             7065

                           ...  RDOMESTICMIG2011  RDOMESTICMIG2012  \
STNAME  CTYNAME            ...
Alabama Autauga County     ...          7.242091         -2.915927
        Baldwin County     ...         14.832960         17.647293
        Barbour County     ...         -4.728132         -2.500690
        Bibb County        ...         -5.527043         -5.068871
        Blount County      ...          1.807375         -1.177622
...                        ...               ...               ...
Wyoming Sweetwater County  ...          1.072643         16.243199
        Teton County       ...         -1.589565          0.972695
        Uinta County       ...        -17.755986         -4.916350
        Washakie County    ...        -11.637475         -0.827815
        Weston County      ...        -11.752361         -8.040059

                           RDOMESTICMIG2013  RDOMESTICMIG2014  \
STNAME  CTYNAME
Alabama Autauga County            -3.012349          2.265971
        Baldwin County            21.845705         19.243287
        Barbour County            -7.056824         -3.904217
        Bibb County               -6.201001         -0.177537
        Blount County             -1.748766         -2.062535
...                                     ...               ...
Wyoming Sweetwater County         -5.339774        -14.252889
        Teton County              19.525929         14.143021
        Uinta County              -6.902954        -14.215862
        Washakie County           -2.013502        -17.781491
        Weston County             12.372583          1.533635

                           RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
STNAME  CTYNAME
Alabama Autauga County            -2.530799     7.606016    -2.626146
        Baldwin County            17.197872    15.844176    18.559627
        Barbour County           -10.543299    -4.874741    -2.758113
        Bibb County                0.177258    -5.088389    -4.363636
        Blount County             -1.369970     1.859511    -0.848580
...                                     ...          ...          ...
Wyoming Sweetwater County        -14.248864     1.255221    16.243199
        Teton County              -0.564849     0.654527     2.408578
        Uinta County             -12.127022   -18.136812    -5.536861
        Washakie County            1.682288   -11.990126    -1.182592
        Weston County              6.935294   -12.032179    -8.040059

                           RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County       -2.722002     2.592270    -2.187333
        Baldwin County       22.727626    20.317142    18.293499
        Barbour County       -7.167664    -3.978583   -10.543299
        Bibb County          -5.403729     0.754533     1.107861
        Blount County        -1.402476    -1.577232    -0.884411
...                                ...          ...          ...
Wyoming Sweetwater County    -5.295460   -14.075283   -14.070195
        Teton County         21.160658    16.308671     1.520747
        Uinta County         -7.521840   -14.740608   -12.606351
        Washakie County      -2.250385   -18.020168     1.441961
        Weston County        12.372583     1.533635     6.935294

[3142 rows x 98 columns]

In [6]:
# Agora, a chave com qualquer boa expressÃ£o idiomÃ¡tica Ã© entender quando ela nÃ£o estÃ¡ ajudando vocÃª. Neste caso, vocÃª pode realmente
# cronometra ambos os mÃ©todos e vÃª qual deles roda mais rÃ¡pido

# Podemos colocar a abordagem em uma funÃ§Ã£o e passar a funÃ§Ã£o para a funÃ§Ã£o timeit para contar o tempo que o
# nÃºmero do parÃ¢metro nos permite escolher quantas vezes queremos executar a funÃ§Ã£o. Aqui vamos apenas configurÃ¡-lo para
# 10
def first_approach():
    global df #nossa variavel pode ser usada fora da funÃ§Ã£o 
    # agora colamos nosso codigo 
    return (df.where(df['SUMLEV']==50)
             .dropna()
             .set_index(['STNAME','CTYNAME'])
             .rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'}))

#vamos ler o nosso conjunto de dados novamente 
df = pd.read_csv('/content/census.csv')

#agora vamos rodar isso 
timeit.timeit(first_approach, number=10)

0.2620929710000155

In [8]:
# Agora vamos testar a segunda abordagem. Como vocÃª pode notar, usamos nossa variÃ¡vel global df na funÃ§Ã£o.
# No entanto, alterar uma variÃ¡vel global dentro de uma funÃ§Ã£o modificarÃ¡ a variÃ¡vel mesmo em um escopo global e nÃ³s
# nÃ£o quero que isso aconteÃ§a neste caso. Portanto, para selecionar apenas nÃ­veis de resumo de 50, crio um novo
# dataframe para esses registros

def second_approach():
    global df
    new_df = df[df['SUMLEV']==50]
    new_df.set_index(['STNAME','CTYNAME'], inplace=True)
    return new_df.rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'})

df = pd.read_csv('/content/census.csv')

timeit.timeit(second_approach, number=10)

0.04716033400006836

In [9]:
# Como vocÃª pode ver, a segunda abordagem Ã© muito mais rÃ¡pida! EntÃ£o, este Ã© um exemplo particular de um tempo clÃ¡ssico
# troca de legibilidade.

# VocÃª verÃ¡ muitos exemplos sobre estouro de pilha e na documentaÃ§Ã£o de pessoas usando encadeamento de mÃ©todos em seus
#panda. E assim, acho que ser capaz de ler e entender a sintaxe realmente vale o seu tempo. Mas mantenha-se
# lembre-se de que seguir o que parece ser expressÃµes idiomÃ¡ticas estilÃ­sticas pode ter problemas de desempenho que vocÃª precisa
# considere tambÃ©m.

In [11]:
# Vamos dar uma olhada em nosso censo DataFrame. Neste DataFrame, temos cinco colunas para estimativas populacionais,
# com cada coluna correspondendo a um ano de estimativas. Ã‰ bastante razoÃ¡vel querer criar alguns novos
# colunas para valores mÃ­nimos ou mÃ¡ximos, e a funÃ§Ã£o apply Ã© uma maneira fÃ¡cil de fazer isso.

# Primeiro, precisamos escrever uma funÃ§Ã£o que receba uma determinada linha de dados, encontre um mÃ­nimo e um mÃ¡ximo
# valores e retorna uma nova linha de dados nd retorna uma nova linha de dados. Chamaremos esta funÃ§Ã£o min_max

def min_max(row):
    data = row[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    return pd.Series({'min': np.min(data), 'max': np.max(data)})


#agora so precisamos aplicar o aply 
# vale lembrar quee se quisermos passar em todas as linhas de todas as colunas 
#temos que passar o eixo = colunas
df.apply(min_max, axis='columns').head()

       min      max
0  4785161  4858979
1    54660    55347
2   183193   203709
3    26489    27341
4    22512    22861

In [12]:
# Claro que nÃ£o hÃ¡ necessidade de se limitar a retornar um novo objeto de sÃ©rie. Se vocÃª estÃ¡ fazendo isso como parte
# de limpeza de dados Ã© provÃ¡vel que vocÃª queira adicionar novos dados ao DataFrame existente. Naquilo
# caso vocÃª apenas pegue os valores das linhas e adicione novas colunas indicando as pontuaÃ§Ãµes mÃ¡xima e mÃ­nima. Isto Ã© um
# parte regular do meu fluxo de trabalho ao trazer dados e construir resumos ou estatÃ­sticas descritivas, e Ã©
# frequentemente usado fortemente com a fusÃ£o de DataFrames.


#aqui vai um exemplo da funÃ§Ã£o onde ela retorna duas novas colunas para inserir no dataframe
def min_max(row):
    data = row[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    # criando uma nova coluna para max e min
    row['max'] = np.max(data)
    
    row['min'] = np.min(data)
    return row
# Agora vamos aplicar ao dataframe a nossa funÃ§Ã£o 
df.apply(min_max, axis='columns')

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,max,min
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594,4858979,4785161
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333,55347,54660
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499,203709,183193
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299,27341,26489
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861,22861,22512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195,45162,43593
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747,23125,21297
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351,21102,20822
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961,8545,8316
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294,7234,7065

In [13]:
#aqui vai um exemplo onde vc pode encadear varias chamadas de apply para criar um  script de manipulaÃ§Ã£o 
#mais sucinto. Um exemplo de uma linha onde vocÃª pode calcular o mÃ¡ximo das colunas
# usando a funÃ§Ã£o aplicar.
rows = ['POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013','POPESTIMATE2014', 
        'POPESTIMATE2015']

#agora vamos aplicar um apply com lambda (lembre que lambda e uma funÃ§Ã£o sem nome de uma linha)
#neste caso ela recebe um Ãºnico parÃ¢metro, x, e retorna um Ãºnico valor, neste
# case o mÃ¡ximo em todas as colunas associadas Ã  linha x.
df.apply(lambda x: np.max(x[rows]), axis=1).head()

0    4858979
1      55347
2     203709
3      27341
4      22861
dtype: int64

In [15]:
# A beleza da funÃ§Ã£o apply Ã© que ela permite flexibilidade em fazer qualquer manipulaÃ§Ã£o que vocÃª
# desejar, pois a funÃ§Ã£o que vocÃª passa para apply pode ser qualquer customizada como vocÃª quiser. Digamos que queremos
# divide os estados em quatro categorias: Nordeste, Centro-Oeste, Sul e Oeste Podemos escrever um
# funÃ§Ã£o que retorna a regiÃ£o com base no estado as informaÃ§Ãµes das regiÃµes do estado sÃ£o obtidas da Wikipedia

def get_state_region(x):
    northeast = ['Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 
                 'Rhode Island','Vermont','New York','New Jersey','Pennsylvania']
    midwest = ['Illinois','Indiana','Michigan','Ohio','Wisconsin','Iowa',
               'Kansas','Minnesota','Missouri','Nebraska','North Dakota',
               'South Dakota']
    south = ['Delaware','Florida','Georgia','Maryland','North Carolina',
             'South Carolina','Virginia','District of Columbia','West Virginia',
             'Alabama','Kentucky','Mississippi','Tennessee','Arkansas',
             'Louisiana','Oklahoma','Texas']
    west = ['Arizona','Colorado','Idaho','Montana','Nevada','New Mexico','Utah',
            'Wyoming','Alaska','California','Hawaii','Oregon','Washington']
    
    if x in northeast:
        return "Northeast"
    elif x in midwest:
        return "Midwest"
    elif x in south:
        return "South"
    else:
        return "West"

In [16]:
# Agora temos a funÃ§Ã£o customizada, digamos que queremos criar uma nova coluna chamada Region, que mostra a
# regiÃ£o do estado, podemos usar a funÃ§Ã£o customizada e a funÃ§Ã£o apply para isso. A funÃ§Ã£o personalizada
# deve funcionar na coluna de nome de estado STNAME. EntÃ£o vamos definir a funÃ§Ã£o apply no nome do estado
# coluna e passe a funÃ§Ã£o customizada para a funÃ§Ã£o apply

df['state_region'] = df['STNAME'].apply(lambda x: get_state_region(x))
#vamos ver o resultado 
df[['STNAME','state_region']].head()

    STNAME state_region
0  Alabama        South
1  Alabama        South
2  Alabama        South
3  Alabama        South
4  Alabama        South